apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-ns
  project: default
  source:
    path: k8/
    repoURL: https://github.com/chaithukrissh/sample-sam-repo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true


