apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
spec:
  destination:
    server: https://34.136.0.179
    namespace: sample-ns
  project: default
  source:
    path: k8/
    repoURL: https://github.com/chaithukrissh/sample-sam-repo.git
    targetRevision: HEAD

